### ISSUE TITLE
Datagram backpressure

### ISSUE THREAD

**Issue by kixelated** [w3c/webtransport#105]
Hey guys, I messed around with the `DatagramTransport` currently available in Chrome Canary. One thing that came up was the interaction between the streams API and datagrams. 

It's possible to pipe a `ReadableStream` to `sendDatagrams`. This code indefinitely sends packets of 1000 bytes which I was using it to benchmark the throughput:

```js
const transport = await new QuicTransport("quic-transport://localhost:443")
await transport.ready

const packet = new ArrayBuffer(1000)
const producer = new ReadableStream({
	pull(controller) {
		controller.enqueue(packet)
	}
})

await producer.pipeTo(transport.sendDatagrams())
```

When the congestion window is hit, `StreamsTransport` must apply backpressure, as it's not possible to drop portions of a stream.

However, it's undefined and not obvious how `DatagramTransport` should react. There are three options:

1. Only call `pull` when there is space in the congestion window. (backpressure)
2. Continuously call `pull` and drop packets when the congestion window is full. (dropping)
3. Continuously call `pull` and queue packets for a maximum duration when the congestion window is full. (queuing)

The nice thing about backpressure is that the application can know when a packet will be dropped prior to reaching the network. Without this information, the application needs to implement it's own congestion control to avoid overwhelming the underlying congestion window.

For example, imagine implementing QUIC streams (or TCP) on top of `DatagramTransport`.

**With backpressure**: the application enqueues the next STREAM frame inside the `pull` function, relying on the underlying congestion control.

**Without backpressure**: the application also needs to compute it's own congestion window to avoid compounding packet loss with retransmissions. If this window is smaller than the underlying congestion control window, it results in lower throughput.

**Comment by ricea** [comment]
Thank you for the feedback.

When I implemented `DatagramTransport` in Chrome I assumed that dropping would be the best approach. But this was based on an incomplete understanding of how QUIC congestion control works.

For practical deployment, we need at least some queuing to avoid dropping packets that would be permitted by congestion control but are a bit too early.

I'm leaning towards also having some backpressure. This needs to be done with care to avoid unnecessary head-of-line blocking, and I don't yet know how it will work in detail.

Whatever we do will have to be precisely described in the specification.

**Comment by jan-ivar** [comment]
I vote for 1 as well, because _"continuously call `pull`"_ seems CPU heavy for no benefit, starving the app of feedback, as OP mentions.

UA's being able to signal upstream "you're sending too fast", seems critical to optimal sending as this `pull` source example shows.

Counterarguments seem to focus on the effect of backpressure on poorly implemented push sources, ones that `write` past not being `writer.ready`, building up a backlog. While discussing how we might mitigate such situations is perhaps not without value, I think it's a distraction.¹

I think we want queueing designed around successful² throughput https://github.com/w3c/webtransport/pull/179#issuecomment-772093452, and that we should tackle the "when do we drop packets?" question separately.

<sub>1. A precedent that seems to supports this is how [BYOB reader works with push sources (no backpressure support)](https://streams.spec.whatwg.org/#example-rbs-push): _"If the consumer does not read data as fast as the socket produces it, the chunks will remain in the stream’s internal queue indefinitely. In this case, using a BYOB reader will cause an extra copy, to move the data from the stream’s internal queue to the developer-supplied buffer. However, if the consumer consumes the data quickly enough, a BYOB reader will allow zero-copy reading directly into developer-supplied buffers"_.</sub>

<sub>2. "Successful" would include low-latency, which I think means smallest queue necessary to support continuous throughput.

**Comment by wilaw** [comment]
Addressed via https://github.com/w3c/webtransport/pull/267
