### ISSUE TITLE
getWriter() access

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport#147]
As raised during TPAC meeting, question was asked why we don't we make the getWriter() method directly accessible from the stream object? 

Current:

```
let stream = await transport.createUnidirectionalStream();
let writer = stream.writable.getWriter();
```

Proposed:

```
let stream = await transport.createUnidirectionalStream();
let writer = stream.getWriter();
```

Argument for was that code becomes cleaner. Argument against was that writeable attribute would still exist on the stream object and hence there would be two identically named methods to access the same writer instance.

**Comment by lgrahl** [comment]
This is a method on [`WritableStream`](https://streams.spec.whatwg.org/#writablestream) which lives in a different spec, so that IMO should be reason enough to not expose a shortcut.

But I see additional reasons why it should not be exposed. It puts an emphasize on the low-level writer, but, optimally you'd chain stream instances together by piping them:

```js
source.readable
        .pipeThrough(encryptStream)
        .pipeThrough(zipStream)
        .pipeTo(sink.writable);
```

If `source` and `sink` are WebTransport streams, `encrypt` and `zip` are streams exposed by the browser, the whole pipeline can ignore the JS thread and run entirely on native code.

**Comment by lgrahl** [comment]
That is my understanding but I'll /cc @domenic @annevk.

**Comment by domenic** [comment]
Yes. This in general goes against the streams design, which tries very hard to separate the streams capability from the writer capability. I'd definitely suggest sticking to the established pattern that all existing streams-based specs use.

If you think this writable stream/writer separation is bad, then it'd be good to open an issue on whatwg/streams to discuss it more generally, so that the ecosystem aligns.

For comparison, this proposal is similar to duplicating a promise's "then" method. E.g. instead of webObject.finished.then(), duplicating then() so you could do webObject.then(). That's pretty weird, I hope you'd agree, and so is this proposal.

**Comment by wilaw** [comment]
Clear arguments made against proposal. Closing as rejected.
