### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by rocallahan** [w3c/webtransport#167]
WebTransport looks great for my application (https://pernos.co) --- we already multiplex multiple streams over Websocket so WebTransport would be a great fit to avoid head-of-line-blocking --- but we benefit from compression a lot. (Currently we use per-message and I think we'd benefit even more from per-stream but our reverse proxy can't do it yet.) Supporting compression state across messages looks tricky with out-of-order delivery but I think it can be done (e.g. see QPACK for QUIC/HTTP3). So, are you planning to support compression directly?

**Comment by LPardue** [comment]
Would it work for you to run a compressor per stream in the application layer? 

I'm not seeing much general purpose benefit from trying to add compression to the transport.

**Comment by rocallahan** [comment]
No, because my streams are short-lived and I want to compress across them.

Basically the Pernosco UI is query-based. Every user action triggers one or more queries, which mostly last for a few seconds at most. Each query generates an (in order, reliable) stream of result packets. Reordering the results of different queries is fine, and desirable to avoid head-of-line-blocking. It is common for queries to return similar or identical results to other queries (e.g., names repeated). I haven't done the analysis to see how much per-stream compression would win by, but I could do that analysis on a result log if you think that would be helpful.

Off the top of my head I don't know of other applications that work this way, but it seems to me to be a logical way to structure client/server interaction.

**Comment by rocallahan** [comment]
Of course we could send binary messages and then try to build cross-stream compression on top of that and maybe we could achieve similar performance to transport-level compression. It's not clear to me whether there are benefits to compressing at the transport level that can't be achieved in JS (other than ease of use/compressor performance, of course).

**Comment by LPardue** [comment]
If you're writing an application you could just optimise around a special-purpose static dictionary. But if that's not enough, wanting a dynamic conmpression context per connection has some challenges. A good document is https://tools.ietf.org/html/draft-handte-httpbis-dict-sec-00.

I sense this is something best left to the applications using WebTransport to figure out for themselves. Common use cases could be fulfilled by some library

**Comment by vasilvv** [comment]
We're currently not planning to add any compression directly to the API, since automatic compression on transport layer has historically led to various security issues (such as CRIME and BREACH).  That said, there's [a proposal](https://github.com/wicg/compression/blob/master/explainer.md) for compression streams that integrates well with WebTransport, so it should be fairly easy to add that on application level.

**Comment by lgrahl** [comment]
Since the API uses streams, it should be trivial to insert a [CompressionStream](https://groups.google.com/a/chromium.org/g/blink-dev/c/JmwpHPTu3XM/m/lel6vSEvBAAJ). If this API is insufficient, a custom `TransportStream` can be created. This is not needed on the transport itself. Separation of concerns. :slightly_smiling_face:

**Comment by wilaw** [comment]
Consensus that compression implemented by application. WG meeting 11/24. Close with no further action.
