### ISSUE TITLE
Consequences of the IETF single protocol decision for connection construction

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport#183]
The IETF WebTransport WG have reached [consensus](https://mailarchive.ietf.org/arch/browse/webtransport/) around the decision to limit WebTransport to be a single protocol _for now_ and for that protocol to be Http3transport. The temporal caveat is important, as we assume that the core notion of WebTransport as a framework in to which other protocols are "plugged" has not been deprecated. 

The API connection constructor has the generic form `new A(B://C)`. We assume that A will be defined by W3C whereas B and C will be defined by the IETF. 

Questions:

1. Will the JS application be able to dictate the protocol being used in a WebTransport connection, or will it simply request a WebTransport connection and the user agent and server will negotiate to find an acceptable protocol? (Much like fetching a Http resource, you may end up using H1, H1.1, H2 or H3)
2. Should the constructor remain new WebTransport(uri) or should it be new Http3Transport(uri)? If the former then the URI will need to differentiate future transports from Http3Transport. 
3. Should the scheme be wt: or https? If WebTransport is conceptually a framework that supports multiple protocols and each protocol is defined by its scheme, then wt: seems a poor choice as it conflates the framework name with the protocol descriptor. The exception here would be if the application cannot choose the underlying protocol being used in which case a wt: scheme would seem appropriate. Issue [180 ](https://github.com/w3c/webtransport/issues/180) seems relevant here. 
4. What's our API plan if IETF in the future decides to define another protocol? Separate constructor? Separate scheme? Detect by uri?

**Comment by jan-ivar** [comment]
To quote https://github.com/w3c/webtransport/issues/180, _"every transport is different"_, I think makes a good point that both the chances and value of correctly predicting that the same interface and constructor will fit future protocols, seem low.

Hopefully, "plugging" isn't about constructor arguments, but about JS code agnosticly working well with different already-created sources and sinks.

At the same time, I like the name `new WebTransport` better, and wouldn't mind hogging it for udp-based http3. YMMV 🤷🏼‍♂️

As for `wt:`, @vasilvv where can I read about that?

**Comment by jan-ivar** [comment]
Meeting:
- Keep the name `new WebTransport`
- Keep an eye on how we identify the server?
- No cookies!
- Remove "pluggable protocols" language in intro

**Comment by lgrahl** [comment]
> Remove "pluggable protocols" language in intro

What was the rationale? This basically throws us back to square one when we want to introduce a new transport. Sure, we can refer to this spec but if it's not designed in a way that allows for easy addition of transports, e.g. by using mixins as described in #180, then it will be a lot of copy & paste or look entirely different.

**Comment by yutakahirano** [comment]
I would like to remove mixins and have flat members as we are focusing on WebTransport over HTTP/3.

**Comment by jan-ivar** [comment]
> > Remove "pluggable protocols" language in intro

[Specifically](https://w3c.github.io/webtransport/#abstract): _"implementing pluggable protocols underneath with common APIs on top"_

With _"[pluggable](https://duckduckgo.com/?q=pluggable&ia=definition)"_ in API design I think people mean a common API _surface_ e.g. constructor) can be reused for multiple things. E.g. through URI scheme `"https"` vs `"quic-transport"` (removed by IETF) constructor args. Ironically, rationale was https://github.com/w3c/webtransport/issues/180. 

The IETF hasn't closed the door on defining future _connection establishment protocols_, so neither have we. At the same time, they're not working on any, so we can't predict whether such a future protocol (if there will ever be one) would need its own constructor or not. If there's some reason you think we must predict it, please share.

Also, some folks thought the language referred to _"on top" protocols_, another word for application framing in messages, which of course can still be done. https://github.com/w3c/webtransport/issues/178#issuecomment-768347316

The organizing principle here seems to be around streams, which is the pattern we hope will aid composition between APIs.

> ... it's not designed in a way that allows for easy addition of transports, e.g. by using mixins

@lgrahl Oh, so by _"pluggable protocols"_ you mean mixins? I think that's separate.

[Mixins](https://heycam.github.io/webidl/#interface-mixin) _"much like [partial interfaces](https://heycam.github.io/webidl/#dfn-partial-interface), are intended for use as a specification editorial aide ... not meant to be exposed"_ [to JS]. As they are not JS observable, we don't break anything by changing our minds now or later. They're a spec organizing tool, available at the discretion of the editors, I believe.

That being said,

> I would like to remove mixins and have flat members as we are focusing on WebTransport over HTTP/3.

@yutakahirano What are the immediate benefits of removing the mixins? If anything, isn't the current breakdown more readable? Mixins may also be used _"possibly across documents"_, so we might consider if other specs want to reuse parts, or be open to breaking them apart again once that happens.

**Comment by ricea** [comment]
> @yutakahirano What are the immediate benefits of removing the mixins? If anything, isn't the current breakdown more readable? Mixins may also be used "possibly across documents", so we might consider if other specs want to reuse parts, or be open to breaking them apart again if that happens.

In my view the mixins are an unnecessary layer of abstraction that add complexity. In practice, we don't even use them in Chrome's implementation. If we find we need them in the future, we can put them back. But there's no reason to bear the burden of that complexity at the moment.

**Comment by jan-ivar** [comment]
What's complex about them? Don't they just break things into chapters, much like partial interface?

**Comment by ricea** [comment]
> What's complex about them? Don't they just break things into chapters, much like partial interface?

1. They result in layering violations because they try to be general, but in practice the steps need to be customised for the protocol. Search the standard for "for QUIC" to see what I mean. This will only get worse when we make the language about stream algorithms precise.
2. They cause several algorithms to involve "action at a distance". For example step 5. of https://w3c.github.io/webtransport/#dom-unidirectionalstreamstransport-createunidirectionalstream. The promise should actually be resolved after step 4 of https://w3c.github.io/webtransport/#initialize-webtransport-over-quic, but the structure of the standard makes this difficult.

**Comment by jan-ivar** [comment]
> They result in layering violations because they try to be general, but in practice the steps need to be customised for the protocol. 

Makes sense. While there's some precedence for using mixins abstractly, they come with cost to maintain. E.g. _"Each AnimationFrameProvider object also has a [target object](https://html.spec.whatwg.org/#concept-animationframeprovider-target-object) that stores the provider's internal state"_.

But I don't see anyone else using mixins for future-proofing. WebIDL even [says](https://heycam.github.io/webidl/#using-mixins-and-partials): _"If you’re only planning to extend a single interface, ... consider using a partial interface instead"_. That's quite pragmatic.

We also don't seem to be in good shape. E.g. I see algorithms referencing internal slots defined on the transport, which doesn't seem like clean separation.

It seems reasonable to me to defer abstraction cost to when a second transport appears. I don't see what we can't fix then.

We still have a lot of algorithms to flesh out, and clearing roadblocks for doing so seems like the right thing to do here.

> Search the standard for "for QUIC" to see what I mean

We should certainly still reference [QUIC-TRANSPORT], but yes, the notion we're coming back here to add "for Transport B", sometime in the future, seems broken. My guess that is better done in some extension spec.

**Comment by yutakahirano** [comment]
> @yutakahirano What are the immediate benefits of removing the mixins? If anything, isn't the current breakdown more readable? Mixins may also be used "possibly across documents", so we might consider if other specs want to reuse parts, or be open to breaking them apart again if that happens.

Yeah, I would like to have a reason to have an additional abstraction layer. We wanted to use mixins for multiple interfaces for multiple protocols (QUIC, HTTP3, HTTP2) before, so it made sense to me to have them. I want to see another reason to keep them now.

**Comment by lgrahl** [comment]
> With _"[pluggable](https://duckduckgo.com/?q=pluggable&ia=definition)"_ in API design I think people mean a common API _surface_ e.g. constructor) can be reused for multiple things. E.g. through URI scheme `"https"` vs `"quic-transport"` (removed by IETF) constructor args. Ironically, rationale was #180.

I follow that rationale (obviously, since I wrote #180) that this form of "pluggability" by a single constructor is harmful. :slightly_smiling_face: 

> @lgrahl Oh, so by _"pluggable protocols"_ you mean mixins? I think that's separate.

Yes.

> The organizing principle here seems to be around streams, which is the pattern we hope will aid composition between APIs.

Absolutely. :+1: However, while it allows to easily switch from thing A that uses byte streams to thing B that uses byte streams, it does not simplify adding further kinds of transports.

> In my view the mixins are an unnecessary layer of abstraction that add complexity. In practice, we don't even use them in Chrome's implementation. If we find we need them in the future, we can put them back. But there's no reason to bear the burden of that complexity at the moment.

Following @jan-ivar's explanation of mixins, it is perfectly fine to omit them in the implementation since they are non-observable in JS anyway. And I agree that, since transports are different, the implementations will look different anyway. I'm not that deep into WebIDL, so pardon me if that conceptional idea violates something of WebIDL: Ideally, we would have the mixin just as an interface with a basic concept with basic rules (byte stream, ordering, etc.) but without any concrete steps that would add abstraction complexity. It's not my intention to put obstacles in your path, just paving it for future transports. A general transport API for the web, which I think the term "WebTransport" clearly conveys, IMO should not become too specialised on a concrete transport (HTTP3).

**Comment by jan-ivar** [comment]
> I'm not that deep into WebIDL, so pardon me if that conceptional idea violates something of WebIDL: Ideally, we would have the mixin just as an interface with a basic concept with basic rules (byte stream, ordering, etc.) but without any concrete steps that would add abstraction complexity.

I can't speak for WebIDL, but in my experience it seems guided by quite pragmatic and often opinionated principles around describing concrete testable code.

Exhibit A: the [Constrainable Pattern](https://w3c.github.io/mediacapture-main/getusermedia.html#interface-definition), which the WebRTC WG wanted to promote as an abstract pattern, on the chance it might be useful outside its sole application in `MediaStreamTrack` (spoiler: it's not. It [barely generalizes across track sources](https://w3c.github.io/mediacapture-main/getusermedia.html#media-track-supported-constraints)).

WebIDL wouldn't even let us declare it, as it caused WPT tooling to fail, since no browsers directly implement this "interface". Thus, we had to escape it using a yellow Example block:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/3136226/108282682-06c79e80-7150-11eb-8cb0-e0d3008d9ead.png">

I'd say WebIDL was right. We had to [contort](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-applyconstraints) spec prose quite a bit to describe what needed to be implemented, and you'll still find the occasional mention of "device" in the abstract prose. We're only now redoing the examples in that section to be practical instead of extolling exotic features of the abstract pattern https://github.com/w3c/mediacapture-main/pull/772

> A general transport API for the web, which I think the term "WebTransport" clearly conveys, IMO should not become too specialised on a concrete transport (HTTP3).

Well, "WebSocket" is over TCP. 😉

I think WebSocket & WebTransport are "general" by being low level, letting apps build _subprotocols_ ontop.

I like the constructor name "WebTransport" over "Http3Transport", because there's a chance future transports (HTTP/4?) may fit when they come along (but there's no guarantee of course, depending what they turn out to be).

> And having a general transport concept/mixin/whatever as a reminder for people working on the spec today or in the future would help, I think.

If the cost was zero, then maybe. But that's not the case. We'll have to remember. We were able to model RTCDataChannel on WebSocket without mixins.
