### ISSUE TITLE
Shall we define transport concept?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#191]
Hi, I'm wondering if we want to define concept-transport, like we have [concept-request](https://fetch.spec.whatwg.org/#requests) and [Request class](https://fetch.spec.whatwg.org/#request-class)
in the fetch spec. Such a separation would be good for describing things like #152. Issues like #185, #128, #79, #93 are related.

I'm thinking about something like https://github.com/w3c/webtransport/commit/acf10eedf0cd094e6c424ae79b49303324331ea0 (for #152 and #185; still WIP).

What do people think?

@aboba @jan-ivar

**Comment by jan-ivar** [comment]
I'm not sure `request` is the right concept. That's a JS input object to fetch, we have no such input. From your patch, this sounds like the datagram writable's _underlying sink_. But other specs seem to make due without actually defining the underlying sink/source as concepts, because there's usually a 1-1 higher-level browser object to attach the [[internal slots]] to.

Even [fetch](https://fetch.spec.whatwg.org/#concept-http-network-fetch) does this: _"9. Let pullAlgorithm be an action that resumes the ongoing fetch if it is suspended. ... 13. Let stream be the result of creating a ReadableStream with pullAlgorithm set to pullAlgorithm ..."_

I would try it without abstractions first, ad I think there's only 4 algorithms.

I would model this on https://w3c.github.io/webrtc-insertable-streams/#stream-creation by hanging all our algorithms off of stream creation of the various streams we create.

* For datagrams, there's only one writer and one reader per transport, and once https://github.com/w3c/webtransport/issues/181 is fixed, the single WritableStream and  single ReadableStream would both be created as part of the creation steps of a new `transport.datgrams` browser object.

* For uni and bi streams, algorithms would be in the the constructors of https://w3c.github.io/webtransport/#outgoingstream and https://w3c.github.io/webtransport/#incomingstream

**Comment by yutakahirano** [comment]
Makes sense, thank you.
