### ISSUE TITLE
Port blocking

### ISSUE THREAD

**Issue by ricea** [w3c/webtransport#229]
We need to ensure that port blocking is applied to avoid security issues like the [NAT Slipstreaming attack](https://samy.pl/slipstream/). This will probably be delegated to the Fetch standard, so this issue is just here to track it and make sure it isn't forgotten.

**Comment by yutakahirano** [comment]
I'm sure that WebTransport people are happy with the current block list, but having an allow-list instead (whatwg/fetch#1189) can be concerning.

**Comment by annevk** [comment]
https://github.com/whatwg/fetch/issues/889 has some thoughts on this. We probably need to distinguish between local and remote ports as well.

**Comment by jan-ivar** [comment]
@yutakahirano What's our "current block list"? I couldn't find any reference to "port" or "ports" in this spec.

**Comment by ricea** [comment]
https://fetch.spec.whatwg.org/#port-blocking is what we're blocking in practice.

**Comment by jan-ivar** [comment]
We probably should call that out in the spec explicitly.

**Comment by jan-ivar** [comment]
Meeting:
- Adam: Probably W3C's responsibility to track this, since IETF may have native implementations where port blocking is not an issue.
- Marking ready for PR to add link to fetch spec per https://github.com/w3c/webtransport/issues/229#issuecomment-972584267
- As follow-up, push on https://github.com/whatwg/fetch/issues/1268 to possibly add a list to source ports as well to the block list that would be shared with WebTransport (more important for UDP/HTTP3 that we control the source port)
- Might be worth sending a mail to IETF (WebTrans & QUIC?) mailing lists requesting clarity on where this belongs?
