### ISSUE TITLE
Do we need writable.reset() for "unreliable streams"?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webtransport#260]
At #242 and #248 we talked about whether we need writable.reset() (or abortWriting) to abort the stream. The conclusion was we don't need it and just using writable.abort() (or writer.abort()) is fine, assuming whatwg/streams/issues/1015 will be resolved.

But @ricea pointed out that it would be useful to make the stream unreliable.

```
const writer = writable.getWriter();
writer.write(data);
await writer.close();
// To suppress retransmission of `data`.
writable.reset();
```

This use case is not covered by writable.abort() because it is no-op when the stream is closed.

See also: #259

**Comment by yutakahirano** [comment]
I prefer having a method that has the stream send RESET_STREAM when it enters [the "Data Sent" state](https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport#section-3.1) - it is better than `reset()` because it doesn't interact with stream states. I'd like to protect the method with lock.

**Comment by yutakahirano** [comment]
Memo for the WG meeting:

 - Do we need to support unreliable streams?
 - If so, is writable.reset() the right API?

See also: #165.

**Comment by ricea** [comment]
I realised another problem with `reset()`: it's hard to manage the stream lifetime if we want to be able to perform operations after `close()`. In Chromium in Blink and the network service we use closing the stream as a signal to forget about it. Only the lower levels of the QUIC stack keep track of the stream long enough to perform retransmissions.

To be able to `reset()` after `close()` would require at least some major restructuring and might introduce some ugly encapsulation violations.

**Comment by aboba** [comment]
@yutakahirano I think there may be potential use case for partial reliability.  WebTransport over HTTP/3 datagrams is only marginally more performant than `RTCDataChannel` in unreliable/unordered mode (due to lower overhead), and less flexible (e.g. no P2P support). 

But WebTransport with partial reliability has an advantage over `RTCDataChannel` reliable/ordered mode because it makes use of QUIC's advances in the transport arena, and we have measurements indicating that it performs considerably better on wireless networks and in situations with substantial loss.

**Comment by jan-ivar** [comment]
Meeting:
- Explore alternatives to `reset`

**Comment by jan-ivar** [comment]
If whatwg/streams/issues/1015 is successful then `abort` is all we need and we can remove `reset`.
