### ISSUE TITLE
In browser support, tunneling TURN traffic over webtransport

### ISSUE THREAD

**Issue by unicomp21** [w3c/webtransport#270]
From a webrtc perspective, would it make sense to have in-browser support for tunneling TURN server traffic over webtransport?  A couple key intentions would be using commonly open firewall ports for tunneled TURN traffic, and also eliminating head of line blocking for tunneled TURN packets.

**Comment by aboba** [comment]
For situations where UDP can traverse the NAT/firewall, we'd be talking about TURN over WebTransport datagrams.  Since WebTransport over HTTP/3 datagrams have higher overhead than UDP, I'm not sure what the advantage would be for WebTransport.  So the potential benefit would seem to lie primarily in situations where UDP is blocked, so that a fallback is needed. This could be TURN over TCP, TURN over TLS or perhaps TURN over WebTransport over HTTP/2.   The advantage for WebTransport over HTTP/2 might be:

1. Potential for TURN over WebTransport over HTTP/2 (fallback) candidates to pass connectivity checks where TURN over TCP or TURN over TLS candidates would fail.  Assuming that the firewall only allows TURN to certain destination ports (e.g. 443).  This might occur in a situation where a DPI firewall won't allow TURN over TLS, but might allow WebTransport over HTTP/2 over TLS.  I suspect this is a very small (and perhaps non-existent) set of circumstances.
2. Saving some connectivity checks and time by having WebTransport try HTTP/3 and fallback to HTTP/2, rather than having separate candidates for each. This seems more plausible.

**Comment by unicomp21** [comment]
@aboba What about head of line blocking when using TCP?  Is there any benefit to eliminating head of line blocking when it comes to TURN traffic?

Excellent point on #2

**Comment by murillo128** [comment]
While minor, I think there might be some benefits of providing TURN over an HTTP based protocol, like [TURN over websockets](https://datatracker.ietf.org/doc/html/draft-chenxin-behave-turn-websocket-01)  😇

Appart of the connectivity, we would get some features that can be shared with rest of the http based service, like http authentication & cookies, origin checks, http redirections, reverse proxying, firewall access list based on FQDNs...

**Comment by unicomp21** [comment]
@murillo128 is TURN over websocket currently available in browsers?

**Comment by murillo128** [comment]
it is just a draft proposal, it never got enough support to go further

**Comment by aboba** [comment]
@murillo128 WebTransport probably won't support authentication & cookies.

**Comment by unicomp21** [comment]
Is there an argument for TURN over HTTP3?  Like mentioned above w/ websockets?

**Comment by unicomp21** [comment]
@aboba @jan-ivar  is this true?
https://webrtchacks.com/zoom-avoids-using-webrtc/

@murillo128 it looks like they went the direction of the TURN/websocket proposal?

I would also be interested in knowing if Zoom has built a special packet engine.  One hack/optimization I can think of is detecting when there is tcp packet loss, and doing things like having a user space tcp stack which chases tunneled udp packets w/ empty packets covering the same sequence numbers to auto fill packet loss on the receiver side, allowing the tunneled udp protocol to be the primary force controlling packet replay/resend.

Anyhow, does the above create an argument for TURN/https3?  Would I be wrong in saying most large corporate firewalls, which do deep packet inspection, are forcing traffic to TURN/TCP?  And this de-optimization will increase as more folks return to the office post covid?

Or am I just totally confused?  And completely wrong?

**Comment by jan-ivar** [comment]
Meeting:
- The answer here is either no, or please ask the IETF.
- Closing.
