### ISSUE TITLE
More thorough state persistence treatment

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#332]
I don't think that this document can put state management out of scope entirely, as [Section 12.2](https://w3c.github.io/webtransport/#state-persistence) attempts to.  It should be relatively simple to reference the connection management of fetch and note that session tickets (and QUIC address validation tokens) will need to be stored according to the storage rules that fetch uses.

**Comment by jan-ivar** [comment]
@aboba can I volunteer you to update this section?

**Comment by aboba** [comment]
Note: The former section 12.2 is now 11.2.  The text in question is: 

"WebTransport by itself does not create any new unique identifiers or new ways to persistently store state, nor does it automatically expose any of the existing persistent state to the server. For instance, none of the transports defined in this document automatically send cookies, support HTTP authentication or caching invalidation mechanisms. Since they use TLS, they may support TLS session tickets, which could be used by the server (though not by passive network observers) to correlate different connections from the same client. This is not specific to WebTransport by itself, but rather an inherent property of all TLS-based protocols; thus, this is out-of-scope for this specification."
