### ISSUE TITLE
Better error for when we can't send a datagram?

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webtransport#36]
When we can't send a datagram due to congestion control, we reject a promise with an InvalidStateError.    But that InvalidStateError doesn't give the app developer much info.  Can we do better?

**Comment by jan-ivar** [comment]
This might be OBE. There's no mention of `InvalidStateError` in the spec regarding datagrams.

Also, the plan for filling the underlying send queue is to prematurely resolve writer promises. If congestion then happens, these datagrams are dropped, but there's no related promise to reject. 

Well-written producers should be respecting back pressure, and not write in the face of congestion.

**Comment by jan-ivar** [comment]
Discussed this at the meeting and with @martinthomson right after.

Say the sender's underlying datagram sink's internal queue is sized to hold 20 datagrams to ensure optimal throughput.

If a producer writes 21 datagrams then 20 promises will resolve and the 21st promise will be pending, creating back pressure on the producer, preventing the queue from building up past 21 entries, for _well-behaved_ JS (we don't think we care that much about poorly behaved JS).

To avoid sending stale data due to congestion, we plan to add something like `datagrams.setSendQueueExpiration(long duration)` in https://github.com/w3c/webtransport/pull/179.

With this in place, the queue should flush pretty quickly once everything on it is expired.

While we could reject the 21st promise, this feels arbitrary. We think expiration is not abnormal, so rejection doesn't make sense. Rejection is left for the connection closing and that sort of thing.
