### ISSUE TITLE
Opening WebTransport streams before the WebTransport session is established

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#409]
This is supported within the WebTransport protocol, but is it fully supported in the API? 

Related to: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/73

**Comment by jan-ivar** [comment]
Meeting:
- Examples show you can call wt.createUnidirectionStream right after construction without awaiting wt.ready, but the promise it returns doesn't resolve until session has been established
- The datagrams example shows writing without waiting on wt.ready (it instead awaits writer.ready which would likely be true since it relies on backpressure in the streams spec, which is unrelated to wt.ready.
-

**Comment by aboba** [comment]
Looking over the specification and the examples, it seems clear that streams can be opened (and datagrams sent) without waiting on wt.ready.  So I think this can be closed (if not, please reopen).
