### ISSUE TITLE
When flow control is blocked

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#426]
Our QUIC implementation takes a very particular approach to how it manages flow control.  In order to avoid flow control deadlocks, which are a serious problem, it does not accept data on streams that have insufficient flow control credit.  This helps us avoid deadlocks in our application protocol code because any code that creates dependent writes can use a rejected write as a signal.  For instance, in QPACK, we attempt to write out QPACK table inserts before we reference them, but if the insert fails, we change to using a literal value.

Our interface also has two write interfaces: one that takes a stream of bytes and reports how many bytes were accepted; and, one that takes a block of bytes and only does anything if the entire block can be written.  We found this to be essential.

What is the attitude of the WebTransport API when it comes to this pattern?  It really isn't clear from the [write](https://w3c.github.io/webtransport/#webtransportsendstream-write) definition.

**Comment by aboba** [comment]
I think we need to look at the [WHATWG Streams spec ](https://streams.spec.whatwg.org/#writable-stream-default-writer-write) for guidance on this. The ready promise would not be resolved until there is flow control credit, but if write is called, the definition doesn't seem to allow the promise to be rejected unless the stream is in an errored state or is closed.

**Comment by martinthomson** [comment]
I don't think that the streams spec is going to cover this use case very well, though I'd be happy to learn otherwise.

**Comment by vasilvv** [comment]
I don't believe there is anything in the API that would prevent the user from calling write() repeatedly.  The buffers on the QUIC layer and the sandbox boundary are limited, meaning those almost certainly end up somewhere inside the tab's JS memory.

**Comment by martinthomson** [comment]
So this isn't just about whether things block, but the nature of the feedback that an app gets, as well as the control it is given.

If an app writes and the API simply withholds resolution of the promise until flow control capacity is available, it will be very easy to write applications that generate flow control deadlocks.  To avoid deadlocks - at least in my opinion - you really need to provide the app with feedback in the form of a rejection.  You also need an interface that lets the app request an atomic write.

As far as I am aware, the API specification takes no position on this topic, to the point that I have no idea what happens if flow control is blocked.  That needs fixing, but as I note, we probably need more than that for applications that need to manage the risk of deadlock.  A byte stream interface is not sufficient.

**Comment by afrind** [comment]
An alternate API is to allow the application to query how many bytes can be written without blocking, but given the subtle nature of flow control deadlocks, it may not be the best choice to prevent them.

**Comment by martinthomson** [comment]
I considered that option, but with concurrent access to the session from multiple threads (yay, workers) and session flow control being shared state, I'm not sure that I would be confident in that approach.

**Comment by jan-ivar** [comment]
> If an app writes and the API simply withholds resolution of the promise until flow control capacity is available, it will be very easy to write applications that generate flow control deadlocks.

Another way to state this perhaps is that JS is going to create dependencies on UA behavior here, which is why I filed #428.

By "deadlock" I assume we merely mean promises not resolving in the time or order an application might expect:
```js
await sendStreamA.write(a);
await sendStreamB.write(b);
```
But that would be a _promise_ API, and we don't have that. Instead, we have a _streams_ API, which discourages that pattern:
```js
const writerA = sendStreamA.getWriter(); // not idempotent
await writerA.write(a);
writerA.releaseLock();
const writerB = sendStreamB.getWriter(); // not idempotent
await writerB.write(b);
writerB.releaseLock();
```
...which is to streams APIs what the `Promise(executorFunction)` constructor was to old callback code: an escape hatch.

Instead, the design of WHATWG streams encourages separating concerns (and code) into time-independent pipes. [E.g.](https://jsfiddle.net/jib1/z965juL7/)
```js
const p1 = readableA.pipeThrough(new TransformStream({controller: codeA}).pipeTo(sendStreamA);
const p2 = readableA.pipeThrough(new TransformStream({controller: codeB}).pipeTo(sendStreamB);
await Promise.all([p1, p2]);
```
Here it's actually quite hard to write code that can deadlock. So I'd argue our choice of WHATWG streams as API helps make it less "easy" to write assumptions that can deadlock. 

I'd concede early demos focused on media probably aren't written that way, especially streams-per-frame ones, where streams seem ill-suited, and I've proposed separate API for those in https://github.com/w3c/webtransport/issues/419 (that [maybe shouldn't use streams](https://github.com/w3c/webtransport/issues/420#issuecomment-1269134910)).

Another way to resolve app assumptions about stream order might be to let apps express them as priorities #62.

> To avoid deadlocks - at least in my opinion - you really need to provide the app with feedback in the form of a rejection. You also need an interface that lets the app request an atomic write.

That sounds like a very different API.

**Comment by martinthomson** [comment]
> That sounds like a very different API.

Yep.  But if you don't do something about this issue, you can have a very bad day.

An example might help.  Let's say that you decide that you want to send a blob of stuff on one stream, then refer to it in some way on another stream.  Ideally, what happens is that you write the blob then the reference, in that order.  

The receiver can then either read the blob, save it, then later see the reference and then use the saved blob.

But let's say that the blob is big and you send it with a length prefix.  What a resource-constrained receiver then might do is -when it sees the blob start - decide not to read it until it needs it.  That is, it leaves it in the buffers/network/sender until it is needed.  Then, when it sees the reference, it reads the blob out and can use it.

That works until you stream the two writes as described.  Because each is independent, you might get - for any reason - the sending of the blob blocked on flow control.  Let's say that the blob length prefix gets through, but the reference doesn't because the blob eats all of the flow control credit.

In this case, the receiver might not release more flow control credit, ever.  Receivers generally hold flow control until data is read.  But the application is deliberately holding the blob in the stack without reading, so any credit that it might release is held until the blob is read.  And the blob won't be read until the application receives the reference is received.  The reference can't be sent because there is no flow control credit for it.

That's a deadlock and a very easy one to create when you start building more complex applications.  There are a number of ways to deadlock a protocol like QUIC when it uses flow control.  One easy rule that helps avoid them is to ensure that dependencies are fully written using only available credit, so that you never create a partial write of something that might be processed atomically.  That's not all, but it helps.

API-level affordances are an important part of any strategy for managing this.  Simply treating everything as an independent stream is a viable way to build an application, but the sorts of complex applications people are contemplating already have this problem.  For instance, layered video codecs are built on dependencies like this.

**Comment by afrind** [comment]
[Martin just beat me to it but I'm pressing send anyways]

If the JS writes A and B to different streams, and B cannot be processed until A is processed, then it's bad if B gets the last bits of flow control and A gets none.  The server may not release the flow control reserved by B until it is processed, and the sender cannot send A until receives the flow control credit.  The application could prevent this by waiting for acknowledgements from the peer that A has been processed before attempting to write B, but this adds a 1-RTT penalty the common case (enough flow control exists for A and B).

Attempting to express this relationship with priorities doesn't necessarily work depending on when priorities are evaluated relative to the consumption of flow control.

QPACK is an example of a QUIC application with these kinds of dependencies, optimizations and possible deadlocks, so it's a real concern.

**Comment by jan-ivar** [comment]
Thanks for the examples! If I understand correctly, flow control is ultimately controlled by a receiver. It's true this spec doesn't mention WINDOW_UPDATE and BLOCKED frames, but BLOCKED is probably observable as back-pressure on the send-stream (after queue is full), or (over time) in per-stream [bytesSent](https://w3c.github.io/webtransport/#dom-webtransportsendstreamstats-bytessent).

> the reference doesn't because the blob eats all of the flow control credit.

This [doc](https://docs.google.com/document/d/1F2YfdDXKpy20WVKJueEf4abn_LVZHhMUMS5gX6Pgjl4/mobilebasic#h.owvet9h0qj15) says: _"Having an overall connection level flow control window means that an individual slow stream (talking to a slow backend for example) won’t completely starve the connection: WINDOW_UPDATEs at the connection level will allow other streams to progress, while the slow stream is blocked from receiving more data."_

**Comment by martinthomson** [comment]
That is only true to the extent that you don't have stream inter-dependencies that act at a higher layer.  Those occur more often than you might like and they can lead to deadlocking as noted.  The QUIC spec doesn't really cover this - though it probably should have - but there is handy text in [QPACK](https://quicwg.org/base-drafts/rfc9204.html#section-2.1.3).

**Comment by aboba** [comment]
@jan-ivar Issue https://github.com/w3c/webtransport/issues/402 related to when `await writer.write(largeBuffer)` resolves, and the discussion in that issue is reflected in the note in Section 6.1.  The description in 6.3 as well as the note seems to suggest that the write promise can resolve even If there is not enough flow control credit for `largeBuffer` to be sent by the QUIC sender. 

Looking at the material on sender back pressure in WHATWG streams, which is governed by the [queueing strategy](https://streams.spec.whatwg.org/#high-water-mark), do we understand what happens next?  I'm assuming that if there is not enough flow control credit to send `largeBuffer` that the `writer.ready` promise would not subsequently resolve.

**Comment by jan-ivar** [comment]
The promise returned from `writer.write()` resolves as soon as data has been queued successfully.
The promise returned from [writer.ready](https://streams.spec.whatwg.org/#default-writer-prototype) blocks for as long as there is [back pressure](https://streams.spec.whatwg.org/#backpressure), which is only released by sending.

[Pipe chains](https://streams.spec.whatwg.org/#pipe-chain) rely on the latter. But nothing prevents an app from calling `writer.write()` directly and multiple times to queue up as much data as it wants.

**Comment by aboba** [comment]
Section 6.3 says: "Such a buffer SHOULD have a fixed upper limit, to carry the backpressure information to the user of [WebTransportSendStream](https://www.w3.org/TR/webtransport/#webtransportsendstream)."  This doesn't seem compatible with "queue up as much data as it wants".

**Comment by jan-ivar** [comment]
There's code between `writer.write()` and our (underlying sink) writeAlgorithm that [explains that](https://streams.spec.whatwg.org/#example-manual-write-batch): 
> You can also write directly to writable streams by acquiring a [writer](https://streams.spec.whatwg.org/#writer) and using its [write()](https://streams.spec.whatwg.org/#default-writer-write) and [close()](https://streams.spec.whatwg.org/#default-writer-close) methods. Since writable streams queue any incoming writes, and take care internally to forward them to the [underlying sink](https://streams.spec.whatwg.org/#underlying-sink) in sequence, you can indiscriminately write to a writable stream without much ceremony:

**Comment by jan-ivar** [comment]
> You also need an interface that lets the app request an atomic write.

Ok, so without tossing out our streams API for most use cases, maybe we could amend it with something like this:
```js
const writer = sendStream.getAtomicWriter();
const sent = await writer.write(data); // returns false if data couldn't be written all-or-nothing
writer.releaseLock();
```
This would lock the stream, and be a custom access API solely on sendStream itself, implemented on top of the default writer (to give us buffering), except any data the sink can't send atomically is dropped without erroring the stream, causing the promise to settle with `false`.

**Comment by jan-ivar** [comment]
> BLOCKED is probably observable as back-pressure on the send-stream (after queue is full), or (over time) in per-stream [bytesSent](https://w3c.github.io/webtransport/#dom-webtransportsendstreamstats-bytessent).

If this is insufficient, would exposing a per-stream `isBlocked` boolean stat help?

**Comment by aboba** [comment]
@jan-ivar In the webcodecs-echo sample, I dumped writer.desiredSize prior to await writer.write(buffer).  writer.desiredSize = 1 every time.  Does this make sense to you?

**Comment by jan-ivar** [comment]
Yes, because to [create a WebTransportSendStream](https://w3c.github.io/webtransport/#webtransportsendstream-create), we _"[Set up](https://streams.spec.whatwg.org/#writablestream-set-up) stream with"_ just 3 arguments (the rest are defaults):

> To set up a newly-[created-via-Web IDL](https://webidl.spec.whatwg.org/#new) [WritableStream](https://streams.spec.whatwg.org/#writablestream) object stream, given an algorithm _**writeAlgorithm**_, an optional algorithm _**closeAlgorithm**_, an optional algorithm _**abortAlgorithm**_, an optional number _**highWaterMark**_ (default 1), an optional algorithm _**sizeAlgorithm**_, perform the following steps.

IOW, _**highWaterMark**_ is 1, and there's no _**sizeAlgorithm**_, which is [the same as](https://streams.spec.whatwg.org/#ws-prototype) _"a [CountQueuingStrategy](https://streams.spec.whatwg.org/#countqueuingstrategy) with a [high water mark](https://streams.spec.whatwg.org/#high-water-mark) of 1"_ (chunk).

This highWaterMark=1 controls the size of our WritableStream's [internal queue](https://streams.spec.whatwg.org/#internal-queues), which sits ahead of, and is different from, our [underlying sink](https://streams.spec.whatwg.org/#underlying-sink) and its internal send buffer of implementation-defined length.

1 is the minimum required to let back pressure signals function between stream objects in pipes, by modifying `desiredSize` above, at, or below zero, creating a series of gates that open and close.

Since the promise from `write()` is resolved when the underlying sink (our [write](https://w3c.github.io/webtransport/#webtransportsendstream-write) algorithm resolves and) has consumed the chunk, it makes sense to me that `desiredSize` is always 1. If you remvoe the `await` I'd expect it to be 0 (or negative if called more than once).

**Comment by jan-ivar** [comment]
That said, if you write fast enough, I'd expect the browser to eventually produce back pressure, [based on](https://w3c.github.io/webtransport/#webtransportsendstream-write) _"Such a buffer SHOULD have a fixed upper limit, to carry the backpressure information to the user of [WebTransportSendStream](https://w3c.github.io/webtransport/#webtransportsendstream)."_

**Comment by jan-ivar** [comment]
You could try experimenting with larger chunk sizes, just watch out for [crbug 1225189](https://crbug.com/1225189).

**Comment by aboba** [comment]
I'll match your WebTransport bug with a WebCodecs bug!

Due to [WebCodecs Issue 584](https://github.com/w3c/webcodecs/issues/584) and the underlying [crbug 13757111 ]()https://bugs.chromium.org/p/chromium/issues/detail?id=1375111) choosing VP9 with `L1T3` produces enormous chunks, up to 200 KB (see the chart).  From what I can tell (will investigate more), desiredSize still =1.  So if there is a fixed upper limit to the buffer, it's quite large.

**Comment by aboba** [comment]
I removed `await` from `writer.write(largeBuffer)` in the WebCodecs-Echo sample.  The glass-glass latency appears to have markedly decreased at high resolutions with complex codecs such as AV1.  Also, reordering is now observed on the receiver side.

Comparison (requires Chrome Canary): 

[With await](https://webrtc.internaut.com/wc/wtSender4/)
[Without await](https://webrtc.internaut.com/wc/wtSender7/)

**Comment by pthatcher** [comment]
Would this be solved by a method called .writeWithoutBuffering() that either writes without buffering or blows up because you tried writing too much?  Could we not just stick that right on the Stream?  This would basically bypass WHATWG streams, but if you want to bypass the buffering, that's basically what you're doing anyway.  

I actually think this would be a nice API coupled perhaps with some kind of property of .amountwritablewithoutbuffering.

**Comment by pthatcher** [comment]
Or I could see something like this:

```
const writer = await sendStream.allocateWriteSpace(message.length());
writer.write(message);
```

**Comment by jan-ivar** [comment]
> ... perhaps with some kind of property of .amountwritablewithoutbuffering.

I believe this was discussed in https://github.com/w3c/webtransport/issues/426#issuecomment-1282587813 above and [rejected](https://github.com/w3c/webtransport/issues/426#issuecomment-1283203492) because workers make it hard to query how many bytes can be written ahead of writing them.

> Would this be solved by a method ... that either writes without buffering or blows up because you tried writing too much? Could we not just stick that right on the Stream? 

I think this is what we need, but how is it different from what I proposed in https://github.com/w3c/webtransport/issues/426#issuecomment-1289868418?

> This would basically bypass WHATWG streams,

What does that mean? I suggested an API that locked the stream first, to avoid having to specify what happens when someone writes using both APIs at once.

> but if you want to bypass the buffering, that's basically what you're doing anyway.

Maybe I missed something, but is frog-leaping the buffer a requirement? It seems to me as long as we fail if the buffer becomes blocked, then we don't inherently need to jump the queue here.
