### ISSUE TITLE
hole punching support

### ISSUE THREAD

**Issue by marten-seemann** [w3c/webtransport#429]
For WebTransport servers / VMs behind firewalls / NATs, it would be desirable to enable WebTransport to punch through them. This issue is **not** an ask to build hole punching capabilities _into_ WebTransport, but just to enable application protocols to run their own hole punching logic on top of WebTransport.

This is currently not possible, since browsers:
1. use a fresh UDP socket (and therefore an unpredictable UDP port) for every outgoing connection
~~2. don't reveal that UDP port until (and only if!) a WebTransport connection is established~~

(1) is not a protocol requirement, QUIC allows multiplexing of multiple connections on the same UDP socket. In my understanding, it's done to be able to use zero-length connection IDs, as well as to decrease linkability between QUIC connections.

~~(2) is an API decision, and I'm wondering if this is something that could be solved: If there was a way for the application to learn the UDP port of the WebTransport connection before the actual connection attempt is started (or, as a hack, even during the connection attempt), it could coordinate the hole punching with the WebTransport server, so that the connection would then be able to pass through the firewall.~~

EDIT: this is wrong. Even if we know the _local_ UDP port, we don't know which port this will get mapped to by the NAT.

**Comment by ricea** [comment]
> (1) is not a protocol requirement, QUIC allows multiplexing of multiple connections on the same UDP socket. In my understanding, it's done to be able to use zero-length connection IDs, as well as to decrease linkability between QUIC connections.

The `allowPooling` option to the constructor permits multiplexing, but I don't know of any clients that actually implement it.

> (2) is an API decision, and I'm wondering if this is something that could be solved: If there was a way for the application to learn the UDP port of the WebTransport connection before the actual connection attempt is started (or, as a hack, even during the connection attempt), it could coordinate the hole punching with the WebTransport server, so that the connection would then be able to pass through the firewall.

There are security and privacy consequences to making this information available. I haven't thought through it in detail, but my instinct is that it would be too dangerous.

**Comment by marten-seemann** [comment]
> The allowPooling option to the constructor permits multiplexing, but I don't know of any clients that actually implement it.

As far as I understand, `allowPooling` is only used to multiplex multiple WebTransport session onto a single QUIC connection, but not multiple QUIC connections onto a single UDP socket. Thus, it wouldn't help with NAT traversal.

**Comment by jan-ivar** [comment]
Using WebTransport between peers seem out of scope from [our charter](https://www.w3.org/2020/12/webtransport-wg-charter.html#scope) which defines our scope to be client-server. I suggest closing this.

**Comment by jan-ivar** [comment]
Meeting:
- a server behind a firewall is effectively peer-to-peer (typically servers are exposed to clients, and clients are not)
-

**Comment by samantp** [comment]
…
> EDIT: this is wrong. Even if we know the _local_ UDP port, we don't know which port this will get mapped to by the NAT.

If we knew the local UDP port earlier, (or better, could specify it) we could use the rendezvous server used for hole punching typically, to relay this port to the server and complete the hole punching. But since this port is not known upfront, the connect to the WTP server will fail. It think allowing this local port to be specified can help wtp used in client server mode in fire walled environments too. Instead of the cumbersome webrtc route.

**Comment by samantp** [comment]
It would be useful for the webtransport() constructor to accept an optional UDP socket creation callback function which can be given access to the UDP socket once that is created. It can be used for initiating UDP hole punching sequence, after which the remaining parts of the WebTransport constructor can proceed successfully, even when the server is behind firewall. 

Otherwise one will need cumbersome webrtc mechanism, which also has the disadvantage of server needing so many UDP ports for multiple clients.
