### ISSUE TITLE
allow opening streams and sending datagrams in parallel to the CONNECT request

### ISSUE THREAD

**Issue by marten-seemann** [w3c/webtransport#435]
WebTransport allows the client to (optimistically) open streams and send datagrams right after issuing the upgrade request, while the CONNECT request is still in flight. This saves one network roundtrip, assuming that the server accepts the WebTransport session. In case the server rejects the upgrade, these streams will be reset and the datagrams will be ignored.

This was recently clarified in the HTTP/3 WebTransport spec: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/80

Currently, this is not possible using the browser API. For example, [`createBidirectionalStream()`](https://w3c.github.io/webtransport/#dom-webtransport-createbidirectionalstream) is specified to wait until the connection state is `"connected"`. It would be really nice if there was a way to make use of this feature from the browser.

**Comment by martinthomson** [comment]
This is potentially an advantage.  If the server redirects, data sent in QUIC-native streams or datagrams might be hard - or even impossible - to replicate properly when re-attempting a connection.  There are any number of reasons why what works on one connection might not work on a subsequent attempt.

The latency hit, which is non-trivial, is unfortunate though.

**Comment by jan-ivar** [comment]
Just because a method returns a promise doesn't mean JS needs to `await` it. I suppose we could reorder [these two steps](https://w3c.github.io/webtransport/#dom-webtransport-createbidirectionalstream):

1. Wait for transport.[[[State]]](https://w3c.github.io/webtransport/#dom-webtransport-state-slot) to be "connected".
2. Let internalStream be the result of [creating a bidirectional stream](https://w3c.github.io/webtransport/#session-create-a-bidirectional-stream) with transport.[[[Session]]](https://w3c.github.io/webtransport/#dom-webtransport-session-slot).

**Comment by jan-ivar** [comment]
> Just because a method returns a promise doesn't mean JS needs to await it.

But yeah you do need to `await` it to get the stream object. 🤦 I'm not awake today.

**Comment by aboba** [comment]
I vote for Option 1 (for `createBidirectionalStream` and `createUnidirectionalStream`). As far as I can tell, nothing else would need to be changed.
