### ISSUE TITLE
MAX_STREAM limit (ingest) (still need an event when stream ids become available again)

### ISSUE THREAD

**Issue by aboba** [w3c/webtransport#446]
Recently on the MoQ WG mailing list, there was a thread relating to interaction of frame/stream transport with the MAX_STREAMS limit.  Imagine a conferencing application implementing a 7x7 grid of videos from each participant.  If 10 QUIC streams needed to be simultaneously open per video stream, then this could yield a requirement for MAX_STREAMS >= 500 just for video. 

How would an application ensure the MAX_STREAMS limit is set to a suitable value for a WebTransport session? 

Pointer to the thread: https://mailarchive.ietf.org/arch/msg/moq/hecXJfwaysqbyp85ZUwAT9I5CM0/

**Comment by martinthomson** [comment]
This would be something that can be adjusted at runtime, but you are right to note that this is probably higher than the default mode that an HTTP client would choose.

Obviously, for upload, the server can just expand as needed, but the client probably needs an API.

**Comment by jan-ivar** [comment]
> Obviously, for upload, the server can just expand as needed, but the client probably needs an API.

Why can't the browser expand as needed?

**Comment by martinthomson** [comment]
This is a limit that the server exercises.  Let's say that the client starts at 100, which is a reasonable starting point for a great many use cases.  But if the server needs 500, the client won't know that 500 unless it is somehow told.  This is true for any starting point, as it seems like any default will - in some cases - be exceeded.

**Comment by jan-ivar** [comment]
Meeting:
- should we report these (server) limits to JS?
- default in Chrome may be 100 for sending?
- partially a resource constraint, partially an application concurrency control
- it is cumulative
- your quic stack would update the limits.
- for server to client direction, the application might want to raise its limit, as client is willing to accept those streams
- for client to server direction, you don't know what the limit is, especially if it's pooled
- example: conferencing app, might have 5 concurrent frames sent at the same time, per media stream. x 10 users, would hit server to client limit.
- concerned about resource attacks on the server, and "give me more" JS apis
- might want a specific error code to say you've exceeded the quota of number of streams.

**Comment by wilaw** [comment]
Per the QUIC spec https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport-18#section-19.11, the Maximum Streams are defined as "A count of the cumulative number of streams of the corresponding type that can be opened over the lifetime of the connection". 

In this thread @martinthomson suggests that 100 might be a reasonable starting point. 

For media applications sending frame-per-stream at 30fps - 120fps, they will exhaust that quota very quickly. 

In the frame-per-stream use-case, will the user-agent keep requesting an ever-higher MAX_STREAMS count? Is the max stream count really cumulative over the life of the WebTransport connection?

**Comment by LPardue** [comment]
I would expect the API to be able to abstract away the actual MAX_STREAMS value sent on the wire. Instead presenting something more like a concurrency target or relative stream count.

Let's be clear that the number of streams one side can open is based on the value of MAX_STREAMS sent by the peer. So if a server needs to send lots, the client needs to send MAX_STREAMS, and vice versa. One way implementations work is to automatically continually send MAX_STREAMS updates as they consume stream data and read up to the FIN or reset offset. Absent that, an application might be given an API to explicitly grant more streams.

**Comment by marten-seemann** [comment]
Here's what I would've liked to say at the IETF meeting, but the queue was closed:

On the browser side, the limit is not interesting in the sense of a DoS defense. For a server, it's trivial to run a DoS attack against a browser.
What we _should_ be thinking about instead is the cases where the limit is actually useful in preventing the browser from getting overwhelmed in a non-attack scenario (example: stream-level flow control when the client is just slow consuming the data).

**Comment by jan-ivar** [comment]
Meeting:
- Negotiation happens when you want more but don't have more.
- Do we need an API for a JS app to do this early? say,
   - "hey I'm about to create a ton of streams per frame to send"
   - "hey I'm preparing to ask the server to send me a ton of streams per frame.
- Maybe server cannot know ahead of time always. e.g. webinar. how many show?
- A client sending 10000 files to a file server
- flip side: when is the limit helping the implementer or the user?
   - some limits relate to flow control. Server wants to limit its commitment and how much data client can send. commitment between endpoints. there for a reason
   - an API can help by giving the server more credits, to send more streams to the server, allowing the server to open more streams
   - the other way would require IETF (no way for outgoing client->server
- constructor arg downside: web conferencing might not know ahead of time, depending on # of participants
- Do we need an API or not? seems to come down to this question: If a client suddenly creates a ton of (short-lived) streams per frame, for, say, live video ingest. Will this cause the client UA to have to renegotiate limits with the server? And will this roundtrip impede on the live-ness of the video (stutter or freeze frames)?
   - If so, then some form of API seems needed
   - If not, then no API needed. Is there research available to learn the answer to this?

**Comment by jan-ivar** [comment]
Someone mentioned Chrome apparently has a max stream limit of 100 for sending? receiving or both?

A good next step is probably to write a test that tries out find these limits to see where they are (we'll need WPT tests for any potential feature here anyway, and this would be good to test).

**Comment by jan-ivar** [comment]
Meeting:
- Do we need:
  - Ability to ask for more streams? (not that much we can do?)
  - If there are none available, rejected in an identifiable way
  - Ask for how many they can use
- A handshake gives you the initial number you're allowed to create (MAX_STREAM_ID) updated by sending MAX_STREAM_FRAMES
- Maybe not force everybody to keep track of that. Instead, maybe expose what UA thinks.
- Having a signal that it didn't open because it hit a limit seems good. Anything more seems hard
- Some kind of error from createBi/UniStream()
- What about incoming? No value?
- What is advantage to having UA limit it?
- That one tab should not bring UA to its knees
- What problem are we solving to add a limit? Probably isn't one.

TODO:
- Need a PR to reject createBi/UniDirectionStream() in a reliable way, when MAX stream limit is hit. Let's app drop its request, OR
- Fire some limitreached event

**Comment by jan-ivar** [comment]
Meeting:
- Should create method fail or block?
- Should we expose the number?
- Should we fire an event?
- All of the above or some combination?
- Doesn't feel great to do both

**Comment by wilaw** [comment]
TPAC discussion - https://www.w3.org/wiki/WebTransport/Meetings2023#WebTransport_TPAC_meeting_-_Seville_2023TPAC and slide at https://docs.google.com/presentation/d/1PzshEzs8GPeoYvVboi-9D0n8ZtXBZHuM7uZe1blahSk/edit#slide=id.g27bc4bd45e1_0_62 

Leaning towards rejecting the promise followed by an event.
Still need to define the default behavior.

**Comment by jan-ivar** [comment]
Meeting:
- ```js
   new WebTransport({incomingPoolSize: 1000000});
   ```
- MAX_LIMIT is an absolute value in the protocol, but the browser is able to raise that limit, and can take into account concurrent streams when deciding when to raise the protocol limited.
-

**Comment by jan-ivar** [comment]
This issue started out discussing server→client (moved to https://github.com/w3c/webtransport/issues/544) but now seems focused on ingest (client→server).
