### ISSUE TITLE
Can we multiplex more than one session per connection in the same browser tab?

### ISSUE THREAD

**Issue by pthatcher** [w3c/webtransport#449]
In discussions about RTP over QUIC, it sounds like there's a possibility that future protocols will use WebTransport session IDs for muxing differing sets of streams and datagrams over one QUIC connection.  And it would be nice for web clients to be able to implement such protocols, or implement its own protocol with the same technique.

However, there is currently (as far as I know) no way create two WebTransport sessions sharing one connection in the same browser tab.

For example, would it be possible to do something like this?

```
let transport = new WebTransport(...);
let transport2 = transport.create_pooled(...);
```

Perhaps this is only possible if the server supports pooling, and maybe that's OK.

**Comment by jan-ivar** [comment]
> However, there is currently (as far as I know) no way create two WebTransport sessions sharing one connection in the same browser tab.

The current API for this would be:
```js
const wt1 = new WebTransport({allowPooling: true, requireUnreliable: true});
const wt2 = new WebTransport({allowPooling: true, requireUnreliable: true});
```
This should work in any browser that supports pooling. What we don't have is a way for apps to fail if they don't get this (e.g. `requirePooling`). Do we need that?

**Comment by aboba** [comment]
@jan-ivar In the example, wt1 and wt2 might be pooled on the same QUIC connection, or they might not be.. To be pooled, both the browser and the server need to support pooling.  So the application can't really control whether multiple sessions are pooled on a single QUIC connection; it's an optimization that might or might not be enabled. 

With respect to RTP over QUIC, it seems like the API already provides applications with the flexibilty they need. If the application wants to multiplex multiple RTP sessions on the same WebTransport session, it can do that.  If it prefer to have each RTP session on a separate QUIC connection, then it can construct multiple WebTransports, each with allowPooling: false.  The only thing that might be tricky is if the application wants to multiplex multiple RTP sessions on the same QUIC connection, but with different sessions.  But what underlying need does this satisfy that can't be provided by multiplexing RTP sessions on the sane QUIC connection within the same session?

**Comment by ekinnear** [comment]
In [other areas](https://www.ietf.org/archive/id/draft-ietf-taps-interface-18.html#groups) that attempt to offer somewhat abstract transport interfaces for this sort of thing, the concept of "cloning" an existing session exists to explicitly request a new session that shares the same underlying transport. This seems analogous to wanting to specify "please pool these two things together". 

That said, I'm not sure that we _want_ to offer a way for an application to control this -- does it provide any meaningful value beyond offering ways for an application to accidentally shoot itself in the foot when the underlying WebTransport implementation might have otherwise chosen to do something better?

**Comment by jan-ivar** [comment]
Meeting:
- As much as we can, we want a connection that's pooled to be indistinguishable from one that isn't.
- Adding this increase the level of complexity without delivering meaningful capabilities
