### ISSUE TITLE
HTTP/2 might be reliable(-only), but datagrams aren't

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#479]
> [...] just double checking that we're clear that datagram delivery will still be unreliable (can take that to a separate issue, though).

_Originally posted by @ekinnear in https://github.com/w3c/webtransport/pull/474#discussion_r1115264044_

The point we might want to make clear is that while datagrams might be reliably delivered over the current connection, there is no guarantee that the other endpoint will use HTTP/2 to deliver them onward to their final destination.

**Comment by aboba** [comment]
I think there may be a problem in the definition of "requireUnreliable": 

requireUnreliable, of type boolean, defaulting to false
When set to true, the WebTransport connection cannot be established over HTTP/2 if an HTTP/3 connection is not possible.

The problem is that requireUnreliable, even if set to true, can't guarantee E2E use of HTTP/3.

**Comment by jan-ivar** [comment]
I believe #474 closes this issue by stating `"supports-unreliable"` only applies to the first hop.
