### ISSUE TITLE
API handling of redirects

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#499]
ietf-wg-webtrans/draft-ietf-webtrans-http3#113 says: "The user agent MUST NOT automatically follow such redirects, as the client could potentially already have sent data for the WebTransport session in question; it MAY notify the client about the redirect."

This is an issue about whether we should, in fact, notify the client about 3xx codes in the API.

**Comment by vasilvv** [comment]
I think the question was whether we should tell the client we got a 3nn status, or whether we should just return an error.

**Comment by jan-ivar** [comment]
Meeting:
- useful for debugging
- Do we need an application to take an algorithmic response to a redirect? E.g. go to a different CDN? e.g. for load balancing. We want to support scalable delivery (different mechanisms in use)
- Do we expose:
  1. that we got a 3xx error?
  2. that we got a 3xx error and the redirect url?
- Don't expose in the API?
- Maybe expose just the code, because an app could respond by going down its DNS list? (but would an app limit itself to only taking this action for a confirmed redirect?)
-

**Comment by wilaw** [comment]
Regarding chair action to ask IETF, we are about to enter a recursive loop as it seems that this question was already addressed via https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/61#issuecomment-1487976956.

Unless a compelling use-case can be provided for exposing the redirect and given the [security concerns](https://github.com/w3c/webtransport/issues/499#issuecomment-1514160249), suggestion for workgroup is that we do not notify the client for now. If future use-cases become apparent which require notification, we can extend the spec at that time.

**Comment by vasilvv** [comment]
The redirect is not intentionally in the protocol, it's just a consequence of it being an HTTP request is that a server can always reply with a 3xx.  "3xx is a fatal error just like 5xx would be" is one possible answer.

**Comment by jan-ivar** [comment]
Meeting:
- No interest in exposing it and no clear use case in doing so.
- We should clarify in our spec that we don't expose this, with a note as to why (echoing https://github.com/w3c/webtransport/issues/499#issuecomment-1514160249)
