### ISSUE TITLE
Should the constructor take http3Only or something more transport agnostic?

### ISSUE THREAD

**Issue by ekinnear** [w3c/webtransport#561]
In 3eb37c8 a long time ago, we appear to have updated to refer to `http3Only` in the constructor, even though elsewhere we talk about ensuring transports that provide unreliability, etc. 

The [WebTransport Overview](https://www.ietf.org/archive/id/draft-ietf-webtrans-overview-06.html) document, in theory, should provide all of the concepts that we'd want to allow developers to request, and if there's something missing we should probably add it there.

Since our general principle was to refer to properties of the transport that we wanted, not any specific underlying protocol, should we clean this up to also follow that same pattern?

**Comment by jan-ivar** [comment]
The constructor options argument is [requireUnreliable](https://w3c.github.io/webtransport/#dom-webtransportoptions-requireunreliable), which seems transport agnostic.

It calls the underlying _"[Initialize WebTransport over HTTP](https://w3c.github.io/webtransport/#initialize-webtransport-over-http)"_ algorithm, which is not agnostic:
<img width="818" alt="image" src="https://github.com/w3c/webtransport/assets/3136226/5f58aa57-e9f6-494e-91e5-8330078fd3e0">
...because it includes a specific steps into [fetch](https://fetch.spec.whatwg.org/#concept-connection-obtain):
<img width="799" alt="image" src="https://github.com/w3c/webtransport/assets/3136226/53e6977d-b1ec-4baf-bf6b-d5aa875eb073">
...where this argument is called _"http3Only"_:
<img width="950" alt="image" src="https://github.com/w3c/webtransport/assets/3136226/6256903b-7955-4d2d-9d6f-6254a1784c93">

This seems like an editorial choice to allow readers to correlate arguments across specs by name and order.

As such, the W3C spec(s) are very much tied to HTTP/3 and HTTP/2 in their specificity right now, even if the API is forward looking. I.e. both fetch and this spec would be expected to update to support e.g. HTTP/4.

**Comment by jan-ivar** [comment]
@ekinnear would opening an issue on fetch to have a more agnostic argument name than `http3Only` be useful? Or would renaming it just on our end help?

**Comment by ekinnear** [comment]
Hmm, good point. Do we have details on the rationale within fetch for it being called `http3Only`?

I could see there being an argument that fetch might be transport specific, whereas WebTransport is trying to be transport-agnostic. Not sure it's a particularly strong argument, though, so aligning the terminology used is probably higher priority.

**Comment by jan-ivar** [comment]
@ekinnear I don't have insight into this, but maybe they haven't thought about it. It couldn't hurt to open an issue with that question.

**Comment by jan-ivar** [comment]
> ... whereas WebTransport is trying to be transport-agnostic.

I don't know that W3C's WebTransport is trying to be transport-agnostic. At the end of the day it details implementation through (today's) fetch.

If the goal is to not come back and fix this spec once HTTP/4 or something is added, we could call this `notHttp2` perhaps to save us a PR, but I'm not sure that gains us much. I suggest either doing that or closing this.

**Comment by aboba** [comment]
It seems hard to predict what changes might be needed for a future HTTP version that doesn't yet exist.  It could require a small modification to the current specification, or it could require more work. `notHttp2` doesn't seem to buy us much, so I'd recommend closing this issue.

**Comment by jan-ivar** [comment]
Meeting:
- No objections to closing @ekinnear does that work?

**Comment by jan-ivar** [comment]
Meeting:
- bikeshed requireUnreliable or unreliableRequired

**Comment by annevk** [comment]
Be careful what you say, because "maybe they haven't thought about it" might include yourself. 😊

http3Only was added in https://github.com/whatwg/fetch/pull/1171.

Anyway, I agree it makes sense to retire that term. I put up https://github.com/whatwg/fetch/pull/1745 to that effect. Given that there's a couple WebTransport specific details, I'd appreciate your thoughts as I suspect it will need a few more tweaks.

Also, maybe this should be reopened until the http3Only term is also fully removed here?

**Comment by annevk** [comment]
Fetch rename has concluded: https://fetch.spec.whatwg.org/#obtain-a-connection-requireunreliable.
