### ISSUE TITLE
How do we identify these things?

### ISSUE THREAD

**Issue by martinthomson** [w3c/webtransport#77]
The current specs assume that URIs are the identifier.  QUIC transport proposes a new scheme.  However that presumes certain things about the transport features and granularity of the identification.  For instance, the current design assumes exclusive access to the entire connection when used with QUIC transport.

A new scheme also has an unfortunate consequence in terms of how we integrate with Fetch and related things like CSP.  WebSockets minted a URI scheme, but the ultimate decision was to erase that and replace it with the equivalent `http://` or `https://` prefix.  This is likely to need a similar sort of allowance.

More seriously, we have an identifier for "something", but we don't really know what that thing is.  We need to understand how all of the things in the protocol might be identified.  Whether that includes details of the protocol *stack* is something we will have to understand.

**Comment by yutakahirano** [comment]
You're talking about https://w3c.github.io/webappsec-csp/#match-schemes, right?
Sorry for being ignorant, can you tell me why we chose to treat ws:// as http://? What happens if we don't treat quic-transport:// as https:// in CSP?

QuicTransport is not HTTP, and using "https://" for QuicTransport looked strange to us, which is why we are proposing a new scheme.

Integrating with Fetch is tricky even without the new scheme because there is not HTTP request/response in the connection setup step.

> More seriously, we have an identifier for "something", but we don't really know what that thing is. We need to understand how all of the things in the protocol might be identified. Whether that includes details of the protocol stack is something we will have to understand.

Sorry, can you elaborate on this a bit more?

**Comment by martinthomson** [comment]
Right, the scheme-part matching in CSP is a horror-show that I would prefer not to extend.  But if we had to, `quic-transport:` scheme-part matching `https:` and `http:` (and `wss:`?) seems tolerable.

The alternative is to use an HTTP URI as the sole basis for identification rather than define these awkward equivalences.

There is more to this than the problems caused by scheme-equivalence.  At the IETF meeting, some people advocated for the ability to multiplex over the same connection.  That complicates the protocol design a little, in the sense that it intrudes in the application's use of the transport in order to identify the resource.  Of course, the current design already interferes with that with the stream 2 origin indication, so an extension of that seems reasonable.

> we have an identifier for "something"

I should correct this.  The current proposal has two different identifiers.  One appears to refer to an HTTP resource that coordinates the creation of a transport-like service over HTTP/3 or HTTP/2.  The other refers to something something QUIC.  That needs to be very precisely defined.  Right now, there is a definition for a scheme and how that information is signaled, but it doesn't define what these mean.

In my view, using `https://` seems preferable to minting a new scheme.  Then there is only the problem of clearly articulating how the resource is used.  We have `Alt-Svc` and the ability for the API to carry hints so that the HTTP transport variants aren't used unnecessarily when QUIC is available.

**Comment by ricea** [comment]
WebSockets using an HTTP handshake led to people confusing it with HTTP, expecting cookies, http auth, etc. to work as with HTTP. This led to feature creep, security issues, and ultimately the ws and wss schemes being rewritten as http and https in many contexts.

QuicTransport is explicitly **not** HTTP, by design. It doesn't use an HTTP handshake, and probably will have no integration with the Fetch standard.

CSP will have to apply. In this respect is more like WebRTC than like WebSockets.

Http3Transport is a different matter, and does use https: URLs.

**Comment by wilaw** [comment]
@martinthomson  - can this be closed given the IETF decision to use http3transport with https as the scheme?

**Comment by martinthomson** [comment]
That sounds right.
