### ISSUE TITLE
Coalesce small writes

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#79]
Imagine an application has a lot of streams open, and writes 100 bytes into each of them in a loop.  Ideally, we would want them to be in the same packet when possible.  However, with current interpretation of the text, they would all result in a new write call into QUIC, and thus each stream write would get its own packet.

My current intuition is that we should bundle all writes within the scope of the current microtask.  I am not sure that this is a well-defined operation, so we might have to just [queue a task](https://html.spec.whatwg.org/#queue-a-task) instead.

**Comment by yutakahirano** [comment]
Do we need to be explicit here? It seems an implementation can bundle multiple QUIC frames in a single packet. https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-13

**Comment by Atrius** [comment]
Being explicit about what gets bundled could be helpful in the datagram case.  For example, if I'm going app-layer FEC on top of lossy datagrams, I probably want to know which datagrams are going to be in the same packet.

**Comment by jan-ivar** [comment]
> ... with current interpretation of the text, they would all result in a new write call into QUIC, and thus each stream write would get its own packet.

What text says this?

Once we flesh out algorithms, all _[OutgoingStream](https://w3c.github.io/webtransport/#outgoingstream)s_ will presumably have their own _underlying sink_ with a queue, which won't preserve chunking anyway https://github.com/w3c/webtransport/issues/189, so it seems reasonable for implementations to be allowed to empty those queues anyway they want, as long as they preserve requirements on order. 

I wouldn't make this JS observable I don't think.

> Being explicit about what gets bundled could be helpful in the datagram case. 

Datagrams would never be bundled, I don't think, because they're datagrams.

**Comment by wilaw** [comment]
https://github.com/w3c/webtransport/issues/185 poses same question. Closing this issue.
