### ISSUE TITLE
Two ways to abort read side of the stream

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport#94]
Apparently WritableStream has an abort() method, which takes a `reason` argument.  It's not entirely clear to me what type is `reason` expected to have, and what are the exact semantics, so it's not entirely clear to me how it should interact with `abortWriting()`.  I suspect we want to have only one of those at the end.

**Comment by ricea** [comment]
What I did for WebSocketStream is treat `abort(reason)` specially if the reason was an object with a `code` property. So if you do `abort({code: 4000, reason: 'stuff'})` it closes with `(4000, 'stuff')`. If you do `abort({code: 4001})` it closes with `(4001, '')`, otherwise `abort({something: 'else'})` would do a normal (no code specified) close.

This is a bit different for QuicTransport because it has separate "close" and "abort" concepts, but I think a similar approach would work.

**Comment by aboba** [comment]
@ricea This seems reasonable. Can be label this as "ready for PR?"

Related to Issue https://github.com/w3c/webtransport/issues/137

**Comment by aboba** [comment]
What about `abortReading()` and `readable.cancel()`? Is it possible to do `readable.cancel({code: 4000, reason: 'stuff'})` ?  If so, then we may not need `abortReading()`.

**Comment by lgrahl** [comment]
My understanding is that the `reason` of `cancel` on the readable stream and `abort` on the writable stream have very similar semantics, so IMO that suggestion seems appropriate.

@ricea I cannot find any documentation for `WebSocketStream` handling `reason` that way? The [WebSocketStream API Design](https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/edit#heading=h.qyzhypmbt4hn) document does not mention arguments for `abort` or `cancel` on the streams.

**Comment by ricea** [comment]
> @ricea I cannot find any documentation for WebSocketStream handling reason that way? The WebSocketStream API Design document does not mention arguments for abort or cancel on the streams.

Oops, sorry about that. I intended to document it, but haven't done so yet.

**Comment by yutakahirano** [comment]
We're removing `abortWriting`/`reset`.
